### PR TITLE
Fix color contrast ratio issues

### LINKED ISSUE #111: Fix color contrast ratio issues
I ran a lighthouse report and the page scored a 95 for accessibility
Screen Shot 2022-09-02 at 12 42 44 PM

We can get that score to 100 by addressing the following issues.

The first issue is for this description here
```

.description {
  color: var(--text-secondary);
  text-align: center;
}
```
Screen Shot 2022-09-02 at 12 45 00 PM

By choosing a dark grey color for the text it will pass the accessibility standards. Anything over 4.5 will pass. 
For example:
Screen Shot 2022-09-02 at 12 46 06 PM

The second issue is here:
```
.primary {
  background-color: var(--primary-section);
}
```
I would suggest changes to a lighter background color(something closer to white)

When both of those changes are applied, then the score should move to 100 in google lighthouse.
Screen Shot 2022-09-02 at 12 52 26 PM

### PR DESCRIPTION
**Pull request by Okibe00**
# Description

Fixed the color contrast ratio issues on the description and primary class to improve the lighthouse accessibility score from 95 to 100
Fixes #111

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [X] I have a descriptive title for my PR
- [X] I have linked this PR to the corresponding issue. [See how to do that here.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [X] I have run the project locally and reviewed the code changes
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Okibe00** [comment]
Hello @jdwilkin4 I couldn't get lighthouse to work when I was done, so I don't really know if the score is 100,  how can I get it to work at my end.

**Comment by jdwilkin4** [comment]
@Okibe00 

Start up the local server on google chrome.
Open up the developer tools.
Here are instructions on how to do that
https://support.google.com/campaignmanager/answer/2828688?hl=en

When it is open, click on the lighthouse tab
Screen Shot 2022-09-05 at 10 28 28 AM


Then click on analyze page load in the right hand corner
Screen Shot 2022-09-05 at 10 29 25 AM

It will probably take a minute or so for the audit to run
Screen Shot 2022-09-05 at 10 29 37 AM

Then you should see the scores
Screen Shot 2022-09-05 at 10 30 51 AM

It looks like the score is up to 100 but it is also important that you run it on your end, to get practice working with lighthouse. 
Hope that helps!

**Comment by Okibe00** [comment]
@jdwilkin4  Thank you, got it to work following your instructions.

**Review by AndreyDmitriev39r — APPROVED** [review]
Yeah, I would do the same. Just going for black and white :)
LGTM

**Review by sparkO7 — APPROVED** [review]
LGTM!

**Pull request merged**
