### PR TITLE
changesFor#83

### PR DESCRIPTION
**Pull request by dgupta0**
# Description

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore items (this includes basic clean up of files, or updates to packages)
- [ ] Updates to documentation

## Checklist

- [ ] I have a descriptive title for my PR
- [ ] I have linked this PR to the corresponding issue. [See how to do that here.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] I have run the project locally and reviewed the code changes
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by jdwilkin4** [comment]
Hi @dgupta0 ! 
Congrats on opening your first PR.

I will let others leave a review for the code but there are a couple of things that I noticed.

No.1:
When creating PR's please make sure to use a descriptive title name so people know that this PR is about.
Here are a couple of examples of good PR titles
https://github.com/DBenMoshe/contrast-ratio-repo/pull/74
https://github.com/DBenMoshe/contrast-ratio-repo/pull/70

No.2:
It looks like you have a merge conflict in your PR.
You will need to resolve it before this PR can be merged.
Here are some good article on how to resolve merge conflicts
https://dev.to/github/how-do-i-resolve-merge-conflicts-5438
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

You can also reach out to in the discord channel if you need help resolving it.

No.3:
Make sure to fill out the PR template here
Screen Shot 2022-08-23 at 7 48 04 AM
It is always best to describe what changes you made so reviewers understand what to look for while reviewing your code.

No.4:
You will need to link the PR to issue you are working on.
You can read about that here
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Hope that helps! 👍

**Review by sparkO7 — CHANGES_REQUESTED** [review]
Hi @dgupta0,
You've done really well for your first PR 👍 

I see you've added two `div`s with the class of `.result-field`. 
Maybe I wasn't clear enough, so that's on me.

Please, go ahead and wrap all the three elements (the `.inputs-row` div, the `h2` and the `.result-row` div) in one single `div` with the class of `.result-field`.

**Comment by dgupta0** [comment]
Hi @jdwilkin4,

Thanks for giving such a descriptive feedback. I will follow the guidelines for resolving conflicts and checklists. 
Thanks again so much!

**Comment by dgupta0** [comment]
Hi @sparkO7, 

I just read the issue again and realised I misread it. It is clearly written that we have to put inputs-row, the h2 and the .result-row in one class. I will make those changes. 

Thank you!!

**Pull request closed without merging**
