### PR TITLE
fix: remove for attribute from inputs

### PR DESCRIPTION
**Pull request by Okibe00**
changes will remove the `for` attribute on both foreground and background input element.

### CODE REVIEW

**Comment by jdwilkin4** [comment]
@Okibe00 

We just started following the conventional commits to make our PR title a little cleaner. 
https://www.conventionalcommits.org/en/v1.0.0/

Please change the title of your PR to `fix: remove for attribute from inputs`

You can edit the title here
Screen Shot 2022-08-09 at 6 02 45 AM

**Comment by jdwilkin4** [comment]
Also don't forget to link your issues to this PR

**Review by jdwilkin4 — APPROVED** [review]

**Comment by Kernix13** [comment]
I suppose that is fine, but what is the reason for removing it? Here is a quote from MDN on the `for` attribute:

> The semantic pairing of `<input>` and `<label>` elements is useful for assistive technologies such as screen readers. By pairing them using the `<label>`'s [for](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#for) attribute, you bond the label to the input in a way that lets screen readers describe inputs to users more precisely.

I'm good either way, but don't we have someone who will be reviewing the accessibility of the project? What would he say?

**Comment by AndreyDmitriev39r** [comment]
@kernix, The way inputs a labels are linked:
label >>> has a for attribute with specific value
input >>> has an id attribute with specific value
thus
the for attribute is not a thing in input element, it's an attribute for the label

**Pull request merged**
